<script>
const SUPABASE_URL='https://jubndqjzpthckxpabtog.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1Ym5kcWp6cHRoY2t4cGFidG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE0MjE5ODEsImV4cCI6MjEwNjk5Nzk4MX0.bgV31GymC0op8yyLwWVJhWDL5kCT69pabnGfOlOhMl0';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
sb.auth.getSession().then(({data:{session}})=>{if(session)showDashboard();else showLogin()});
sb.auth.onAuthStateChange((_e,session)=>{if(session)showDashboard();else showLogin()});
function showLogin(){document.getElementById('loginView').style.display='block';document.getElementById('dashboardView').style.display='none'}
function showDashboard(){document.getElementById('loginView').style.display='none';document.getElementById('dashboardView').style.display='block';loadMetrics();loadPhotoSlots();loadPromos();if(document.getElementById('tab-ranking'))loadRankingHistory();checkSchema()}
async function doLogin(){const email=document.getElementById('loginEmail').value.trim();const pass=document.getElementById('loginPass').value;const errEl=document.getElementById('loginError');errEl.style.display='none';const{error}=await sb.auth.signInWithPassword({email,password:pass});if(error){errEl.textContent=error.message;errEl.style.display='block'}}
async function doLogout(){await sb.auth.signOut()}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
document.querySelectorAll('.tab').forEach(tab=>{tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));tab.classList.add('active');document.getElementById('tab-'+tab.dataset.tab).classList.add('active')})});
async function checkSchema(){const{error}=await sb.from('rankings').select('id').limit(1);if(error&&error.code==='PGRST205')document.getElementById('schemaAlert').style.display='block'}
async function loadMetrics(){const{data,error}=await sb.from('page_views').select('id,viewed_at');if(error){document.getElementById('metricTotal').textContent='0';document.getElementById('metricToday').textContent='0';return}const total=data.length;const today=new Date().toISOString().slice(0,10);const todayCount=data.filter(r=>r.viewed_at&&r.viewed_at.slice(0,10)===today).length;document.getElementById('metricTotal').textContent=total;document.getElementById('metricToday').textContent=todayCount}
const PHOTO_SLOTS=[{id:'hero_1',label:'Carrossel — Imagem 1',section:'carousel'},{id:'hero_2',label:'Carrossel — Imagem 2',section:'carousel'},{id:'hero_3',label:'Carrossel — Imagem 3',section:'carousel'},{id:'hero_4',label:'Carrossel — Imagem 4',section:'carousel'},{id:'hero_5',label:'Carrossel — Imagem 5',section:'carousel'},{id:'menu_below',label:'Abaixo Ver Cardapio',section:'menu'},{id:'gallery_1',label:'Galeria — Imagem 1',section:'gallery'},{id:'gallery_2',label:'Galeria — Imagem 2',section:'gallery'},{id:'gallery_3',label:'Galeria — Imagem 3',section:'gallery'},{id:'gallery_4',label:'Galeria — Imagem 4',section:'gallery'}];
async function loadPhotoSlots(){const{data,error}=await sb.from('photos').select('*');const map={};if(!error&&data)data.forEach(p=>{map[p.slot_id]=p});const render=(slot,container)=>{const photo=map[slot.id];const imgUrl=photo?sb.storage.from('site-images').getPublicUrl(photo.storage_path).data.publicUrl:'';const div=document.createElement('div');div.className='slot-card';div.innerHTML=`${imgUrl?`<img src="${imgUrl}" class="slot-preview" alt="">`:`<div class="slot-preview" style="display:grid;place-items:center;font-size:.6rem;color:var(--muted)">Vazio</div>`}<div class="slot-info"><div class="slot-title">${slot.label}</div><div style="font-size:.75rem;color:var(--muted)">${photo?'Atualizada: '+new Date(photo.created_at).toLocaleDateString('pt-BR'):'Nenhuma imagem'}</div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><label class="btn btn-outline" style="padding:6px 12px;font-size:.7rem;cursor:pointer">${photo?'Substituir':'Enviar'}<input type="file" accept="image/*" style="display:none" onchange="uploadSlotPhoto('${slot.id}',this)"></label>${photo?`<button class="btn btn-danger" style="padding:6px 12px;font-size:.7rem" onclick="deleteSlotPhoto('${slot.id}','${photo.storage_path}')">Remover</button>`:''}</div>`;container.appendChild(div)};const cEl=document.getElementById('carouselSlots'),mEl=document.getElementById('menuSlot'),gEl=document.getElementById('gallerySlots');cEl.innerHTML='';mEl.innerHTML='';gEl.innerHTML='';PHOTO_SLOTS.forEach(s=>{if(s.section==='carousel')render(s,cEl);else if(s.section==='menu')render(s,mEl);else if(s.section==='gallery')render(s,gEl)})}
async function uploadSlotPhoto(slotId,input){if(!input.files.length)return;const file=input.files[0];const ext=file.name.split('.').pop();const path=`slots/${slotId}_${Date.now()}.${ext}`;const{error:upErr}=await sb.storage.from('site-images').upload(path,file,{cacheControl:'3600',upsert:true});if(upErr){showToast('Erro ao enviar: '+upErr.message);return}const{error:dbErr}=await sb.from('photos').upsert({slot_id:slotId,storage_path:path,alt_text:slotId,sort_order:0,active:true},{onConflict:'slot_id'});if(dbErr){showToast('Erro ao salvar: '+dbErr.message);return}showToast('Foto atualizada!');loadPhotoSlots()}
async function deleteSlotPhoto(slotId,storagePath){if(!confirm('Confirma remocao?'))return;if(storagePath)await sb.storage.from('site-images').remove([storagePath]);await sb.from('photos').delete().eq('slot_id',slotId);showToast('Foto removida');loadPhotoSlots()}
async function loadPromos(){const{data,error}=await sb.from('promotions').select('*').order('created_at',{ascending:false});const tbody=document.querySelector('#promosTable tbody');tbody.innerHTML='';if(error||!data)return;data.forEach(p=>{const now=new Date().toISOString().slice(0,10);const isActive=p.active&&(p.start_date<=now)&&(!p.end_date||p.end_date>=now);const tr=document.createElement('tr');tr.innerHTML=`<td>${p.title||'—'}</td><td style="font-size:.75rem;color:var(--muted)">${p.start_date||'?'} → ${p.end_date||'∞'}</td><td class="${isActive?'status-active':'status-inactive'}">${isActive?'Ativa':'Inativa'}</td><td style="white-space:nowrap"><button class="btn btn-outline" style="padding:4px 10px;font-size:.7rem;margin-right:4px" onclick="editPromo(${p.id})">Editar</button><button class="btn btn-outline" style="padding:4px 10px;font-size:.7rem;margin-right:4px" onclick="togglePromo(${p.id},${!p.active})">${p.active?'Desativar':'Ativar'}</button><button class="btn btn-danger" style="padding:4px 10px;font-size:.7rem" onclick="deletePromo(${p.id})">Excluir</button></td>`;tbody.appendChild(tr)})}
async function savePromo(){const id=document.getElementById('promoId').value;const record={title:document.getElementById('promoTitle').value.trim(),description:document.getElementById('promoDesc').value.trim(),button_text:document.getElementById('promoBtnText').value.trim(),button_url:document.getElementById('promoBtnUrl').value.trim(),start_date:document.getElementById('promoStart').value||null,end_date:document.getElementById('promoEnd').value||null,active:true};let error;if(id){({error}=await sb.from('promotions').update(record).eq('id',id))}else{({error}=await sb.from('promotions').insert(record))}if(error){showToast('Erro: '+error.message);return}showToast(id?'Promocao atualizada!':'Promocao criada!');clearPromoForm();loadPromos()}
async function editPromo(id){const{data,error}=await sb.from('promotions').select('*').eq('id',id).single();if(error||!data)return;document.getElementById('promoId').value=data.id;document.getElementById('promoTitle').value=data.title||'';document.getElementById('promoDesc').value=data.description||'';document.getElementById('promoBtnText').value=data.button_text||'';document.getElementById('promoBtnUrl').value=data.button_url||'';document.getElementById('promoStart').value=data.start_date||'';document.getElementById('promoEnd').value=data.end_date||'';document.getElementById('promoFormTitle').textContent='Editar Promocao';document.querySelector('[data-tab="promos"]').click()}
async function togglePromo(id,active){await sb.from('promotions').update({active}).eq('id',id);loadPromos()}
async function deletePromo(id){if(!confirm('Confirma exclusao?'))return;await sb.from('promotions').delete().eq('id',id);showToast('Promocao excluida');loadPromos()}
function clearPromoForm(){document.getElementById('promoId').value='';document.getElementById('promoTitle').value='';document.getElementById('promoDesc').value='';document.getElementById('promoBtnText').value='';document.getElementById('promoBtnUrl').value='';document.getElementById('promoStart').value='';document.getElementById('promoEnd').value='';document.getElementById('promoFormTitle').textContent='Nova Promocao'}
let rankingPreviewData=null;
async function loadRankingHistory(){const tbody=document.querySelector('#rankingHistoryTable tbody');if(!tbody)return;tbody.innerHTML='<tr><td colspan="4" style="color:var(--muted)">Carregando...</td></tr>';const{data,error}=await sb.from('rankings').select('id,period_label,status,published_at').order('published_at',{ascending:false});tbody.innerHTML='';if(error||!data||data.length===0){tbody.innerHTML='<tr><td colspan="4" style="color:var(--muted)">Nenhum ranking publicado ainda.</td></tr>';return}data.forEach(r=>{const tr=document.createElement('tr');const pubDate=r.published_at?new Date(r.published_at).toLocaleDateString('pt-BR'):'—';const statusClass=r.status==='published'?'status-active':'status-inactive';const statusLabel=r.status==='published'?'Publicado':'Rascunho';tr.innerHTML=`<td>${r.period_label||'—'}</td><td class="${statusClass}">${statusLabel}</td><td>${pubDate}</td><td><button class="btn btn-outline" style="padding:4px 10px;font-size:.7rem" onclick="viewRanking(${r.id})">Ver</button></td>`;tbody.appendChild(tr)})}
function maskPhoneLastFour(phone){if(!phone)return'—';const digits=String(phone).replace(/\D/g,'');if(digits.length<4)return digits;return'final '+digits.slice(-4)}
function normalizeHeader(h){return(h||'').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[^a-z0-9]/g,'')}
function detectDelimiter(text){const firstLine=text.split('\n')[0]||'';const commas=(firstLine.match(/,/g)||[]).length;const semis=(firstLine.match(/;/g)||[]).length;return semis>commas?';':','}
function parseCSV(text){const delimiter=detectDelimiter(text);const lines=text.trim().split('\n').map(l=>l.trim()).filter(l=>l);if(lines.length<2)throw new Error('Arquivo vazio ou sem dados suficientes.');const headers=lines[0].split(delimiter).map(normalizeHeader);const idxName=headers.findIndex(h=>/cliente|nome|customer/.test(h));const idxPhone=headers.findIndex(h=>/telefone|celular|whatsapp|phone/.test(h));const idxOrders=headers.findIndex(h=>/pedido|order|quantidade|total/.test(h));if(idxName===-1)throw new Error('Coluna de nome/cliente nao encontrada no CSV.');if(idxOrders===-1)throw new Error('Coluna de pedidos/quantidade nao encontrada no CSV.');const rows=[];for(let i=1;i<lines.length;i++){const cols=lines[i].split